version: '3.8'
services:
  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
    
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
      - MONGODB_URI=mongodb://mongo:27017/ml-playground
    depends_on:
      - ml-service
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo-data: